"""Pytest test suite for the Spaceship class.

Coverage targets:
    - Construction: valid and invalid combinations of all three attributes
    - Properties: getters, setters, type guards, boundary values
    - Dunder methods: __str__, __repr__, __eq__, __lt__, __le__,
      __gt__, __ge__, __bool__, __hash__
    - Edge cases: boundary exact values, whitespace handling, bool
      subclass rejection, float promotion for shield

Original file generated by ChatGPT GPT-5.5.
"""

import pytest
from spaceship import Spaceship


# ---------------------------------------------------------------------------
# Shared fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def default_ship() -> Spaceship:
    """A valid mid-range Spaceship used across many tests."""
    return Spaceship(name="Avalon", hp=500, shield=0.75)


@pytest.fixture
def low_ship() -> Spaceship:
    """A ship with low HP and zero shields."""
    return Spaceship(name="Dart", hp=100, shield=0.0)


@pytest.fixture
def high_ship() -> Spaceship:
    """A ship with high HP and full shields."""
    return Spaceship(name="Colossus", hp=9999, shield=1.0)


# ===========================================================================
# 1. Construction
# ===========================================================================


class TestConstruction:
    """Happy-path construction and attribute round-trips."""

    def test_valid_construction_stores_attributes(self, default_ship):
        assert default_ship.name == "Avalon"
        assert default_ship.hp == 500
        assert default_ship.shield == 0.75

    def test_name_whitespace_stripped_on_construction(self):
        ship = Spaceship(name="  Nova  ", hp=200, shield=0.5)
        assert ship.name == "Nova"

    def test_min_name_length_accepted(self):
        ship = Spaceship(name="ACE", hp=1, shield=0.0)
        assert ship.name == "ACE"

    def test_max_name_length_accepted(self):
        name = "A" * 20
        ship = Spaceship(name=name, hp=1, shield=0.0)
        assert ship.name == name

    def test_hp_of_one_accepted(self):
        ship = Spaceship(name="Min", hp=1, shield=0.0)
        assert ship.hp == 1

    def test_shield_zero_accepted(self):
        ship = Spaceship(name="Min", hp=1, shield=0.0)
        assert ship.shield == 0.0

    def test_shield_one_accepted(self):
        ship = Spaceship(name="Max", hp=1, shield=1.0)
        assert ship.shield == 1.0

    def test_shield_int_promoted_to_float(self):
        ship = Spaceship(name="Int", hp=1, shield=1)
        assert isinstance(ship.shield, float)
        assert ship.shield == 1.0


# ===========================================================================
# 2. name property
# ===========================================================================


class TestNameProperty:
    """Type enforcement, length boundaries, and whitespace rules for name."""

    # --- type errors --------------------------------------------------------

    @pytest.mark.parametrize("bad_value", [123, 3.14, None, [], True, False])
    def test_name_wrong_type_raises_type_error(self, bad_value):
        with pytest.raises(TypeError, match="name must be a str"):
            Spaceship(name=bad_value, hp=1, shield=0.0)

    # --- value errors -------------------------------------------------------

    def test_name_empty_string_raises_value_error(self):
        with pytest.raises(ValueError, match="empty or whitespace"):
            Spaceship(name="", hp=1, shield=0.0)

    def test_name_whitespace_only_raises_value_error(self):
        with pytest.raises(ValueError, match="empty or whitespace"):
            Spaceship(name="   ", hp=1, shield=0.0)

    def test_name_too_short_after_strip_raises_value_error(self):
        # Two visible chars surrounded by spaces — stripped to 2, below MIN
        with pytest.raises(ValueError, match="between 3 and 20"):
            Spaceship(name=" AB ", hp=1, shield=0.0)

    def test_name_exactly_two_chars_raises_value_error(self):
        with pytest.raises(ValueError, match="between 3 and 20"):
            Spaceship(name="AB", hp=1, shield=0.0)

    def test_name_too_long_raises_value_error(self):
        with pytest.raises(ValueError, match="between 3 and 20"):
            Spaceship(name="A" * 21, hp=1, shield=0.0)

    # --- setter via attribute assignment ------------------------------------

    def test_name_setter_updates_value(self, default_ship):
        default_ship.name = "Orion"
        assert default_ship.name == "Orion"

    def test_name_setter_strips_whitespace(self, default_ship):
        default_ship.name = "  Vega  "
        assert default_ship.name == "Vega"

    def test_name_setter_rejects_bad_type(self, default_ship):
        with pytest.raises(TypeError):
            default_ship.name = 99

    # --- boundary exact values ----------------------------------------------

    def test_name_length_exactly_3_accepted(self):
        Spaceship(name="ABC", hp=1, shield=0.0)

    def test_name_length_exactly_20_accepted(self):
        Spaceship(name="B" * 20, hp=1, shield=0.0)

    def test_name_length_21_rejected(self):
        with pytest.raises(ValueError):
            Spaceship(name="C" * 21, hp=1, shield=0.0)


# ===========================================================================
# 3. hp property
# ===========================================================================


class TestHpProperty:
    """Type enforcement and positivity constraint for hp."""

    # --- type errors --------------------------------------------------------

    @pytest.mark.parametrize("bad_value", [1.0, "100", None, [], 1+2j])
    def test_hp_wrong_type_raises_type_error(self, bad_value):
        with pytest.raises(TypeError, match="hp must be an int"):
            Spaceship(name="Err", hp=bad_value, shield=0.0)

    def test_hp_bool_true_raises_type_error(self):
        """bool is a subclass of int — must be explicitly rejected."""
        with pytest.raises(TypeError, match="hp must be an int"):
            Spaceship(name="Err", hp=True, shield=0.0)

    def test_hp_bool_false_raises_type_error(self):
        with pytest.raises(TypeError, match="hp must be an int"):
            Spaceship(name="Err", hp=False, shield=0.0)

    # --- value errors -------------------------------------------------------

    def test_hp_zero_raises_value_error(self):
        with pytest.raises(ValueError, match="positive integer"):
            Spaceship(name="Err", hp=0, shield=0.0)

    def test_hp_negative_raises_value_error(self):
        with pytest.raises(ValueError, match="positive integer"):
            Spaceship(name="Err", hp=-1, shield=0.0)

    def test_hp_large_negative_raises_value_error(self):
        with pytest.raises(ValueError):
            Spaceship(name="Err", hp=-9999, shield=0.0)

    # --- setter -------------------------------------------------------------

    def test_hp_setter_updates_value(self, default_ship):
        default_ship.hp = 250
        assert default_ship.hp == 250

    def test_hp_setter_rejects_float(self, default_ship):
        with pytest.raises(TypeError):
            default_ship.hp = 250.0

    def test_hp_setter_rejects_zero(self, default_ship):
        with pytest.raises(ValueError):
            default_ship.hp = 0

    # --- boundary -----------------------------------------------------------

    def test_hp_of_one_is_minimum_valid(self):
        ship = Spaceship(name="Min", hp=1, shield=0.0)
        assert ship.hp == 1


# ===========================================================================
# 4. shield property
# ===========================================================================


class TestShieldProperty:
    """Type enforcement and [0.0, 1.0] bounds for shield."""

    # --- type errors --------------------------------------------------------

    @pytest.mark.parametrize("bad_value", ["0.5", None, [], 1+0j])
    def test_shield_wrong_type_raises_type_error(self, bad_value):
        with pytest.raises(TypeError, match="shield must be a float"):
            Spaceship(name="Err", hp=1, shield=bad_value)

    def test_shield_bool_true_raises_type_error(self):
        """bool subclass must be rejected before the int/float isinstance check."""
        with pytest.raises(TypeError, match="shield must be a float"):
            Spaceship(name="Err", hp=1, shield=True)

    def test_shield_bool_false_raises_type_error(self):
        with pytest.raises(TypeError, match="shield must be a float"):
            Spaceship(name="Err", hp=1, shield=False)

    # --- value errors -------------------------------------------------------

    def test_shield_below_zero_raises_value_error(self):
        with pytest.raises(ValueError, match="between"):
            Spaceship(name="Err", hp=1, shield=-0.001)

    def test_shield_above_one_raises_value_error(self):
        with pytest.raises(ValueError, match="between"):
            Spaceship(name="Err", hp=1, shield=1.001)

    def test_shield_large_negative_raises_value_error(self):
        with pytest.raises(ValueError):
            Spaceship(name="Err", hp=1, shield=-99.0)

    # --- setter -------------------------------------------------------------

    def test_shield_setter_updates_value(self, default_ship):
        default_ship.shield = 0.25
        assert default_ship.shield == 0.25

    def test_shield_setter_promotes_int_to_float(self, default_ship):
        default_ship.shield = 1
        assert isinstance(default_ship.shield, float)
        assert default_ship.shield == 1.0

    def test_shield_setter_rejects_bool(self, default_ship):
        with pytest.raises(TypeError):
            default_ship.shield = True

    # --- boundary exact values ----------------------------------------------

    def test_shield_exactly_zero_accepted(self):
        ship = Spaceship(name="Min", hp=1, shield=0.0)
        assert ship.shield == 0.0

    def test_shield_exactly_one_accepted(self):
        ship = Spaceship(name="Max", hp=1, shield=1.0)
        assert ship.shield == 1.0

    def test_shield_just_below_zero_rejected(self):
        with pytest.raises(ValueError):
            Spaceship(name="Err", hp=1, shield=-1e-10)

    def test_shield_just_above_one_rejected(self):
        with pytest.raises(ValueError):
            Spaceship(name="Err", hp=1, shield=1.0 + 1e-10)


# ===========================================================================
# 5. __str__
# ===========================================================================


class TestStr:
    """Human-readable string output."""

    def test_str_contains_name(self, default_ship):
        assert "Avalon" in str(default_ship)

    def test_str_contains_hp(self, default_ship):
        assert "500" in str(default_ship)

    def test_str_contains_shield_percentage(self, default_ship):
        assert "75.0%" in str(default_ship)

    def test_str_exact_format(self, default_ship):
        assert str(default_ship) == "Spaceship | Name: 'Avalon' | HP: 500 | Shield: 75.0%"

    def test_str_zero_shield(self, low_ship):
        assert "0.0%" in str(low_ship)

    def test_str_full_shield(self, high_ship):
        assert "100.0%" in str(high_ship)

    def test_str_reflects_updated_hp(self, default_ship):
        default_ship.hp = 123
        assert "123" in str(default_ship)

    def test_str_reflects_updated_shield(self, default_ship):
        default_ship.shield = 0.5
        assert "50.0%" in str(default_ship)


# ===========================================================================
# 6. __repr__
# ===========================================================================


class TestRepr:
    """Developer representation and eval round-trip."""

    def test_repr_contains_class_name(self, default_ship):
        assert repr(default_ship).startswith("Spaceship(")

    def test_repr_contains_name(self, default_ship):
        assert "name='Avalon'" in repr(default_ship)

    def test_repr_contains_hp(self, default_ship):
        assert "hp=500" in repr(default_ship)

    def test_repr_contains_shield(self, default_ship):
        assert "shield=0.75" in repr(default_ship)

    def test_repr_is_eval_round_trippable(self, default_ship):
        reconstructed = eval(repr(default_ship), {"Spaceship": Spaceship})
        assert reconstructed == default_ship


# ===========================================================================
# 7. __eq__
# ===========================================================================


class TestEq:
    """Equality based on all three attributes."""

    def test_equal_ships_are_equal(self):
        a = Spaceship(name="Avalon", hp=500, shield=0.75)
        b = Spaceship(name="Avalon", hp=500, shield=0.75)
        assert a == b

    def test_same_object_is_equal_to_itself(self, default_ship):
        assert default_ship == default_ship

    def test_different_name_not_equal(self):
        a = Spaceship(name="Avalon", hp=500, shield=0.75)
        b = Spaceship(name="Orion", hp=500, shield=0.75)
        assert a != b

    def test_different_hp_not_equal(self):
        a = Spaceship(name="Avalon", hp=500, shield=0.75)
        b = Spaceship(name="Avalon", hp=499, shield=0.75)
        assert a != b

    def test_different_shield_not_equal(self):
        a = Spaceship(name="Avalon", hp=500, shield=0.75)
        b = Spaceship(name="Avalon", hp=500, shield=0.74)
        assert a != b

    def test_eq_with_non_spaceship_returns_not_implemented(self, default_ship):
        result = default_ship.__eq__("not a ship")
        assert result is NotImplemented

    def test_eq_with_none_is_false(self, default_ship):
        assert default_ship != None  # noqa: E711


# ===========================================================================
# 8. Comparison operators (__lt__, __le__, __gt__, __ge__)
# ===========================================================================


class TestComparisons:
    """HP-based ordering operators."""

    @pytest.fixture
    def weak(self):
        return Spaceship(name="Weak", hp=100, shield=0.0)

    @pytest.fixture
    def mid(self):
        return Spaceship(name="Midl", hp=500, shield=0.5)

    @pytest.fixture
    def strong(self):
        return Spaceship(name="Strn", hp=900, shield=1.0)

    @pytest.fixture
    def twin(self):
        """Same HP as mid, different name/shield."""
        return Spaceship(name="Twin", hp=500, shield=0.0)

    # __lt__
    def test_lt_lower_hp(self, weak, mid):
        assert weak < mid

    def test_lt_higher_hp_false(self, mid, weak):
        assert not (mid < weak)

    def test_lt_equal_hp_false(self, mid, twin):
        assert not (mid < twin)

    def test_lt_non_spaceship_returns_not_implemented(self, mid):
        assert mid.__lt__(42) is NotImplemented

    # __le__
    def test_le_lower_hp(self, weak, mid):
        assert weak <= mid

    def test_le_equal_hp(self, mid, twin):
        assert mid <= twin

    def test_le_higher_hp_false(self, strong, mid):
        assert not (strong <= mid)

    def test_le_non_spaceship_returns_not_implemented(self, mid):
        assert mid.__le__(42) is NotImplemented

    # __gt__
    def test_gt_higher_hp(self, strong, mid):
        assert strong > mid

    def test_gt_lower_hp_false(self, weak, mid):
        assert not (weak > mid)

    def test_gt_equal_hp_false(self, mid, twin):
        assert not (mid > twin)

    def test_gt_non_spaceship_returns_not_implemented(self, mid):
        assert mid.__gt__(42) is NotImplemented

    # __ge__
    def test_ge_higher_hp(self, strong, mid):
        assert strong >= mid

    def test_ge_equal_hp(self, mid, twin):
        assert mid >= twin

    def test_ge_lower_hp_false(self, weak, mid):
        assert not (weak >= mid)

    def test_ge_non_spaceship_returns_not_implemented(self, mid):
        assert mid.__ge__(42) is NotImplemented

    # sorting integration
    def test_sorted_ascending_by_hp(self, weak, mid, strong):
        fleet = [strong, weak, mid]
        assert sorted(fleet) == [weak, mid, strong]

    def test_min_returns_lowest_hp(self, weak, mid, strong):
        assert min(weak, mid, strong) is weak

    def test_max_returns_highest_hp(self, weak, mid, strong):
        assert max(weak, mid, strong) is strong


# ===========================================================================
# 9. __bool__
# ===========================================================================


class TestBool:
    """Operational status: True when shield > 0, False when shield == 0."""

    def test_bool_true_when_shield_positive(self, default_ship):
        assert bool(default_ship) is True

    def test_bool_true_at_minimal_shield(self):
        ship = Spaceship(name="Tiny", hp=1, shield=1e-9)
        assert bool(ship) is True

    def test_bool_false_when_shield_zero(self, low_ship):
        assert bool(low_ship) is False

    def test_bool_false_after_shield_depleted(self, default_ship):
        default_ship.shield = 0.0
        assert bool(default_ship) is False

    def test_bool_true_after_shield_restored(self, low_ship):
        low_ship.shield = 0.01
        assert bool(low_ship) is True

    def test_bool_used_in_if_statement(self, default_ship, low_ship):
        assert default_ship  # truthy
        assert not low_ship  # falsy


# ===========================================================================
# 10. __hash__
# ===========================================================================


class TestHash:
    """Hash consistency and usability in sets and dict keys."""

    def test_equal_ships_have_same_hash(self):
        a = Spaceship(name="Avalon", hp=500, shield=0.75)
        b = Spaceship(name="Avalon", hp=500, shield=0.75)
        assert hash(a) == hash(b)

    def test_hash_is_integer(self, default_ship):
        assert isinstance(hash(default_ship), int)

    def test_ship_usable_as_dict_key(self, default_ship):
        registry = {default_ship: "active"}
        assert registry[default_ship] == "active"

    def test_ship_usable_in_set(self):
        a = Spaceship(name="Avalon", hp=500, shield=0.75)
        b = Spaceship(name="Avalon", hp=500, shield=0.75)
        c = Spaceship(name="Orion", hp=300, shield=0.5)
        fleet_set = {a, b, c}
        assert len(fleet_set) == 2  # a and b are duplicates

    def test_different_ships_likely_have_different_hashes(self):
        a = Spaceship(name="AAA", hp=1, shield=0.0)
        b = Spaceship(name="BBB", hp=2, shield=0.5)
        # Not guaranteed by spec, but true for any reasonable implementation
        assert hash(a) != hash(b)

    def test_hash_unchanged_after_identical_reassignment(self, default_ship):
        h_before = hash(default_ship)
        default_ship.name = "Avalon"
        default_ship.hp = 500
        default_ship.shield = 0.75
        assert hash(default_ship) == h_before
